# Generated by Django 2.2.1 on 2019-09-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0002_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
